# Assignment \#1

**Due:** Friday, October 16 at 11:59 pm PT

**Objective:**
This assignment will give you experience using a Google Colab notebook to write text and code, including variables, mathematical operations, and string manipulations.

**Instructions:**
1. This version of the assignment cannot be edited. To save an editable version, copy this Colab file to your individual class Google Drive folder ("OCEAN 215 - Autumn '20 - {your name}") by right clicking on this file and selecting "Move to".
2. Open the version you copied.
3. Complete the assignment by writing and executing text and code cells as specified. **For this assignment, do not use any features of Python that have not yet been discussed in the lessons or class sessions.**
4. When you're finished and are ready to submit the assignment, simply save the Colab file ("File" menu –> "Save") before the deadline, close the file, and keep it in your individual class Google Drive folder.
5. If you need more time, please see the section "Late work policy" in the syllabus for details.

**Honor code:** In the space below, you can acknowledge and describe any assistance you've received on this assignment, whether that was from an instructor, classmate (either directly or on Piazza), and/or online resources other than official Python documentation websites like docs.python.org or numpy.org. Alternatively, if you prefer, you may acknowledge assistance at the relevant point(s) in your code using a Python comment (#).

*Acknowledge assistance here:*

## Question 1 (8 points)

Would it make the most sense to use a Colab notebook ('A'), Jupyter notebook ('B'), Python script ('C'), or the Python command line ('D') for the following purposes?

To provide your answers, create variables below and assign to them a string with each answer. For instance:

In [ ]:
question_1_part_6 = 'C'   # this would indicate you've chosen a Python script for part (6) of the question

Scenarios:
1. Exploring data you just collected from the ocean while conducting field work aboard a ship.
2. Quickly testing out a new Python function or package with a single line of code.
3. Writing sturdy code to regularly load and modify batches of data files that are generated in an identical format on a daily basis by a satellite.
4. Loading a fairly small data set, working up a preliminary analysis, and sharing the code and results with a teammate.

In [ ]:
# Provide your answers below:

## Question 2 (6 points)

Although the goal of OCEAN 215 is not to teach "data science" per se, we hope this course will give you a window into the possibilities offered by data analysis. If you find that you enjoy working with data and writing computer code, you might want to consider a career in academic research or data science. But what is data science, precisely? To better understand this rapidly-growing field, we would like you to read the following article (which should take about 15 minutes), then answer the questions below. There are no wrong answers, but please respond thoughtfully with 1-3 sentences for each (2 points each).

**Article:** "What is data science?" *Thinkful.* https://www.thinkful.com/blog/what-is-data-science/. Read up until the "Your Turn" section. 

1. What data do you think you have generated today that might, at some point, be analyzed by a data scientist?

2. Can you think of an oceanography data set that could be considered "big data"? Why would it be classified as such?

3. The article describes how machine learning can be useful for making predictions and identifying relationships in data. Can you think of a research question or task in oceanography or your academic area of interest that might benefit from machine learning? Why might machine learning be particularly useful for that task?

*Provide your responses here:*

## Question 3 (10 points)

Look at the following table of monthly weather averages in Honolulu, HI.  (Source: [Google](https://www.google.com/search?rlz=1C5CHFA_enUS757US757&ei=oO90X-KsFdaU-gTg1paYCw&q=average+monthly+temperature+Honolulu&oq=average+monthly+temperature+Honolulu&gs_lcp=CgZwc3ktYWIQAzICCAAyBAgAEB4yBggAEAgQHjoECAAQRzoECAAQDVDCEVjIFWCoHGgAcAN4AIABPYgBdJIBATKYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab&ved=0ahUKEwji_KHr4JHsAhVWip4KHWCrBbMQ4dUDCA0&uact=5))

\\

|  Month   |      High T (˚F) | Low T (˚F) | 
|----------|:-------------:|:-------------:|
| January  |  81 |  65 |
| February |  81 |  65 |
|  March   |  82 |  67 |
|  April   |  83 |  68 |
|   May    |  85 |  69 |
|  June    |  86 |  72 |
|  July    |  87 |  73 |
| August   |  88 |  73 |
| September|  88 |  73 |
| October  |  87 |  72 |
| November |  84 |  70 |
| December |  82 |  67 |

\\

Answer the following questions using Python code. Please have your code output (print) something for each part. This output should start with the question part – e.g. print('Part 1:',...) – and include the specified lists or calculations and the answers to questions.

1. Create and print a list containing the high temperatures for each month. What is the object type of the values inside of your list?
2. Create and print a new list with the original high temperatures converted into ˚C. If you do not know the conversion equation, feel free to look it up online, but acknowledge the source. What is the object type of the values inside of your new list?
3. What part of the conversion triggered this change in object type, and why? Print your answer (1 sentence).
4. In your new list from Part 2, replace the temperature in December with a temperature that is 1˚C colder. Print this list.
5. Create a list containing the low temperatures for each month. 
6. Calculate the average low temperature (˚F).
7. Sort the low temperature list from low to high.

In [ ]:
# Provide your answers below:

## Question 4 (9 points)
Challenger Deep, at a depth of 36,200 feet, is known as the deepest part of the ocean (source: [NOAA Ocean Facts](https://oceanservice.noaa.gov/facts/oceandepth.html)). Answer the following questions using Python code. Please have your code output (print) the solutions to each part, including the units! Start your output with the question part, e.g. print('Part 1:',...). If you do not know a conversion factor, feel free to look it up online, but acknowledge the source.

1. Convert the depth of Challenger Deep to miles.
2. Convert the depth of Challenger Deep to km.
3. Find the pressure in atm at the bottom of Challenger Deep. (Hint: 1 atm is approximately 10.33 m)
4. Convert the pressure to Pa. (Hint: 1 atm is approximately 101325 Pa)
5. Convert the pressure to dbar. (Interesting fact: depths in oceanographic data are often specified in dbar instead of meters. Despite pressure not being the same thing as depth, the pressure at 1000 m depth is nearly – but not exactly – equivalent to 1000 dbar. You can confirm this near-equivalence by comparing your answer here to Part 2.)
6. If a particle is sinking at a constant rate from the surface to the bottom of the ocean above Challenger Deep at 0.1 mm/s, how many days will it take to reach the bottom?

In [ ]:
# Provide your answers below:

## Question 5 (10 points)
Ribosomal RNA (rRNA) gene sequencing is often used in phylogenetic research. Each sequence is made up of combinations of 4 different nucleobases, adenine (A), cytosine (C), guanine (G), and uracil (U). Every species of bacteria and archaea has a slightly-unique version of its 16s rRNA gene. This means that 16s rRNA can be targeted to classify what marine bacteria are present in a given parcel of seawater.

In the code box below, there are two strings containing different DNA gene sequences, which differ from RNA in that they contain thymine (T) nucleobases rather than uracil (U). Answer the following questions using Python. Please have your code output (print) the solutions to each, including any strings you are asked to create or slice. Start your output with the question part, e.g. print('Part 1:',...).

1. How many nucleobases are in each of the sequences?
2. How many times does adenine (A) occur in each of the sequences?
3. Do four thymine (T) nucleobases ever occur side-by-side in either of the sequences? Provide your answers as booleans.
4. Create and print two new rRNA sequences by replacing the thymine (T) bases with uracil (U) bases in both DNA sequences.
5. Slice and print the first 24 nucleobases from the new rRNA sequences. How many of each nucleobase (A,C,G,U) are in each of these shorter sequences?

In [ ]:
# Keep these starting lines of code – these may not be changed:
DNA1 = 'GGGGGGCAGCAGTGGGGAATATTGGGCAATGGACGAAAGTCTGACCCAGCCATGCCGCGTGTGTGAAGAAGGCTCTAGGGTTGTAATGCACTTTAAGTAGGGAGGAAAGGTTGTGTGTTAATAGCACATAGCTGTGACGTTACCTACAGAATAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGTTATTTAAGCTAGATGTGAAAGCCCAGGGCTCAACCTTGGAATTGCATTTAGAACTGGGTAGCTAGAGTACAAGAGAGGGTGGTGGAATTTCCAGTGTAGCGGTGAAATGCGTAGAGATTGGAAGGAACATCAGTGGCGAAGGCGGCCACCTGGATTGATACTGACGCTGAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCCAGTAGTCCT'
DNA2 = 'GGGGCGCAGCAGTGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCGCTTTCAGTTGTGAGGAAAGGGGTGTAGTTAATAGCTACATCCTGTGACGTTAGCAACAGAAGAAGCACCGGCTAACTTCGTGCCAGCAGCCTCGGTAATACGAGGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTTCGTAGGCGGTTTGTTAAGCAAGATGTGAAAGCCCTGGGCTCAACCTGGGAACTGCATTTTGAACTGGCAAACTAGAGTACTGTAGAGGGTGGTGGAATTTCCAGTGTAGCGGTGAAATGCGTAGAGATTGGAAGGAACATCAGTGGCGAAGGCGGCCACCTGGACAGATACTGACGCTGAGGAACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTAGTAGTCTG'

# Provide your answers below:

## Question 6 (7 points)

In the code box below, there is a list of [rorqual whales](https://www.britannica.com/animal/rorqual) containing both their common name, their scientific name as a sub-list separated into genus and species, and their estimated populations (source: [The International Whaling Commission](https://iwc.int/status)). As before, begin your answers with the question part, e.g. print('Part 1:',...).

1. How many species are in this list?
2. Replace each of the inner scientific name sub-lists with a single string containing both the genus and the species separated by a space. Convert the population estimate strings to integers and replace them in the list. Make these changes "in-place," that is, without creating a new list. Print the updated list.
3. Remove the information about the Antarctic minke whale from the end of the list and insert it at the beginning of the list. Ensure that the overall format of the list stays the same.

In [ ]:
# Keep these starting lines of code – these may not be changed:
rorqual_whales = [['Blue whale',['Balaenoptera','musculus'],'8000'],
                  ['Bryde\'s whale',['Balaenoptera','brydei'],'90000'],
                  ['Common minke whale',['Balaenoptera','acutorostrata'],'200000'],
                  ['Fin whale',	['Balaenoptera','physalus'],'90000'],
                  ['Sei whale',	['Balaenoptera','borealis'],'50000'],
                  ['Antarctic minke whale',['Balaenoptera', 'bonaerensis'],'510000']]

# Provide your answers below:

## Question 7 (optional, for extra credit: 5 points)

This is a coding puzzle. Write **4 or fewer lines of code** (to follow the 3 lines provided) such that, after executing the code:
* the variable 'x' will be equal to 44,
* the variable 'y' will be equal to 4,
* and the variable 'z' will be equal to 40.

Here's the catch: the code you write may contain mathematical operations (for instance, z = x + y), but **may not contain any numbers** and **may not add a variable to itself** (for instance, z = x + x).

In [ ]:
# Keep these starting lines of code – these may not be changed:
x = 4
y = 12
z = 'Hello'

# Write your own code below: